### ISSUE TITLE
Feature Request: Expose verifying signatures via GitHub Actions `owner` & `repo`

### ISSUE THREAD

**Issue by viccuad** [kubewarden/verify-image-signatures#24]
### Is your feature request related to a problem?

As supported in policy-server and verification config, support verifying signatures performed in GitHub Actions.

Needs https://github.com/kubewarden/policy-sdk-rust/issues/41
Blocks https://github.com/kubewarden/policy-fetcher/issues/91

### Solution you'd like

Support a new type of signature in settings:

```yaml
signatures:
  - image: "*"
    GitHubActions: 
      - owner: octocat
      - repo: test-repo # optional
    annotations: #optional
      env: prod
```

This will make use of the `v1/verify` callback with the new `CallbackRequestType::SigstoreGithubActionsVerify{}`.
