### ISSUE TITLE
Feature Request: Update policy verify-image-signatures to support certificates

### ISSUE THREAD

**Issue by zosocanuck** [kubewarden/verify-image-signatures#39]
### Is your feature request related to a problem?

Support for policies based on single public keys will be difficult to manage especially in larger deployments where they may be many code signing keys/certificates.  

### Solution you'd like

Enhance the verify-image-signatures plugin to support both certificates and certificate chains.

An example policy could be:

```
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: verify-image-signatures-policy
spec:
  module: registry://ghcr.io/kubewarden/policies/verify-image-signatures:v0.1.7
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    signatures:
      - image: "*" # match all tags 
          cert:
            - "-----BEGIN CERTIFICATE-----..."
```
 This could also be extended to support a policy where you specify a CA chain, and any code signing certificates trusted by that chain could be used to validate the policy.
