### ISSUE TITLE
Certificate verification: allow multiple certificates to be added to the same signature

### ISSUE THREAD

**Issue by flavio** [kubewarden/verify-image-signatures#49]
Currently the configuration for the certificate-based verification (not yet released) is the following one:

```yaml
signatures:
  - image: "registry-testing.svc.lan/kubewarden/pod-privileged:v0.1.9"
    certificate: |
      -----BEGIN CERTIFICATE-----
      XXX
      -----END CERTIFICATE-----
    certificateChain:
    - |
      -----BEGIN CERTIFICATE-----
      <intermediate cert>
      -----END CERTIFICATE-----
    - |
      -----BEGIN CERTIFICATE-----
      <root CA>
      -----END CERTIFICATE-----
    requireRekorBundle: true
```

As you can see this takes just 1 certificate.

The public key verification has instead the following configuration:

```yaml
signatures:
  - image: "ghcr.io/kubewarden/*"
    pubKeys: 
      - "-----BEGIN PUBLIC KEY-----xxxxx-----END PUBLIC KEY-----"
      - "-----BEGIN PUBLIC KEY-----xxxxx-----END PUBLIC KEY-----"
    annotations: #optional
      env: prod
```

Which basically states: all the images from "ghcr.io/kubewarden/*" must be signed by these two keys.

Let's assume we want to do something similar: all the images coming from XYZ must be signed by these two certificates, which also happen to be signed by the same CA (because they are both employees of the same company).
Doing something like that would make the whole configuration extremely verbose, because the CAs (which are the same) would have to be repeated twice.

I propose to allow the following configuration format:

```yaml
signatures:
- image: registry-testing.svc.lan/kubewarden/pod-privileged:v0.1.9
  certificate:
  - |
    -----BEGIN CERTIFICATE-----
    CERT1
    -----END CERTIFICATE-----
  - |
    -----BEGIN CERTIFICATE-----
    CERT2
    -----END CERTIFICATE-----
  certificateChain:
  - |
    -----BEGIN CERTIFICATE-----
    <intermediate cert>
    -----END CERTIFICATE-----
  - |
    -----BEGIN CERTIFICATE-----
    <root CA>
    -----END CERTIFICATE-----
  requireRekorBundle: true
```
